### ISSUE TITLE
mariuszgromada/MathParser.org-mXparser

### ISSUE THREAD

**Issue by mariuszgromada** [uhub/awesome-java#2]
Thanks for putting 'mariuszgromada/MathParser.org-mXparser' on 'awesome-c-sharp' list :-) I just starred the 'awesome-c-sharp' and 'awesome-java' repos :-) I just want to inform that 'mariuszgromada/MathParser.org-mXparser' is originally maintained for java. I am keeping both java and c# implementation (C# lib is a port of java lib). Libraries are having exactly the same functionally irrespectively of framework / platform. Maybe it would be good to add 'mariuszgromada/MathParser.org-mXparser' to 'awesome-java' as well?

Best regards :-)

**Comment by ccding** [comment]
It is not included because Java repos typically have way more stars than C# repos. The number of stars of the MathParser project is significantly smaller than the lower bound of the Java list.

**Comment by mariuszgromada** [comment]
Thanks for the information - if this is condition then everything is clear.

**Comment by mariuszgromada** [comment]
Hi - number of stars increased a lot - currently it is 141 :-) Pls let me know whether this satisfies lower bound. 

best regards

**Comment by ccding** [comment]
Check other projects in this repo. There is no lower bound--the ranking of all the java projects in Github matters.

**Comment by mariuszgromada** [comment]
i.e. https://github.com/vvakame/JsonPullParser is in the repo and has
watch: 12, star: 120, fork: 19

my project https://github.com/mariuszgromada/MathParser.org-mXparser has 
watch: 14, star: 141, fork: 35
